all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
      ansible_user: root
      ansible_become: true
    bob.minions.local:
    kevin.minions.local:
    stuart.minions.local:
    jumpy.minions.local:
    gru.minions.local:
  children:
    lxdhosts:
      hosts:
        localhost:
          ansible_host: localhost
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
          ansible_user: root
          ansible_become: true
    lxdcontainers:
      hosts:
        bob.minions.local:
        kevin.minions.local:
        stuart.minions.local:
        jumpy.minions.local:
        gru.minions.local:
